version: '3.8'

services:
  # PostgreSQL service for storing MLflow metadata
  bike_postgres:
    build: "./dockerfiles/postgres"
    image: bike_postgres_system
    container_name: bike_postgres
    restart: always
    environment:
      POSTGRES_USER: bike_airflow  # Username for PostgreSQL
      POSTGRES_PASSWORD: bike_airflow  # Password for the PostgreSQL user
      POSTGRES_DB: bike_mlflow_db  # Name of the database to create
    ports:
      - "5433:5432"  # Maps PostgreSQL port to the host (changed to 5433 to avoid conflict)
    volumes:
      - bike_db_data:/var/lib/postgresql/data  # Persistent volume for PostgreSQL data
    networks:
      - backend  # Connects PostgreSQL to the backend network
    healthcheck:
      # Healthcheck to ensure PostgreSQL is ready before other services start
      interval: 60s
      test: ["CMD", "pg_isready", "-U", "bike_airflow"] 
      timeout: 20s
      retries: 3

  # MinIO service to act as an S3-compatible storage for MLflow artifacts
  bike_minio:
    image: minio/minio:latest  # Uses the official MinIO image
    container_name: bike_minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: bike_minio  # Access key for MinIO (made unique)
      MINIO_SECRET_KEY: bike_minio123  # Secret key for MinIO (made unique)
    command: server /data --console-address ":9001"  # Starts MinIO with the console accessible at :9001
    ports:
      - "9002:9000"  # Maps MinIO's main service port (changed to 9002 to avoid conflict)
      - "9003:9001"  # Maps MinIO's console port (changed to 9003 to avoid conflict)
    volumes:
      - bike_minio_data:/data  # Persistent volume for MinIO storage
    networks:
      - backend  # Connects MinIO to the backend network
      - frontend  # Connects MinIO to the frontend network for potential external access
    healthcheck:
      # Healthcheck to ensure MinIO is ready before other services start
      test: ["CMD", "curl", "-f", "http://localhost:9002/minio/health/live"]  
      interval: 60s
      timeout: 20s
      retries: 3

  # MLflow service for tracking experiments and storing artifacts
  bike_mlflow:
    build: "./dockerfiles/mlflow"  # Builds the MLflow image from the Dockerfile in the specified path
    image: bike_mlflow
    container_name: bike_mlflow
    restart: always
    depends_on:
      bike_postgres:
        condition: service_healthy  # Ensures MLflow only starts after PostgreSQL is ready
      bike_minio:
        condition: service_healthy  # Ensures MLflow only starts after MinIO is ready
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://bike_minio:9000  # URL for the MinIO service (acts as the S3 storage)
      AWS_ACCESS_KEY_ID: bike_minio  # MinIO access key (made unique)
      AWS_SECRET_ACCESS_KEY: bike_minio123  # MinIO secret key (made unique)
      # PostgreSQL connection string for MLflow metadata
      BACKEND_STORE_URI: postgresql://bike_airflow:bike_airflow@bike_postgres:5432/bike_mlflow_db  
      ARTIFACT_ROOT: s3://bike_mlflow/  # Root location for storing artifacts in MinIO
    ports:
      - "5001:5000"  # Maps MLflow's UI port to the host (changed to 5001 to avoid conflict)
    networks:
      - backend  # Connects MLflow to the backend network
      - frontend  # Connects MLflow to the frontend network
    command: >
      mlflow server 
      --backend-store-uri ${BACKEND_STORE_URI} 
      --default-artifact-root ${ARTIFACT_ROOT} 
      --host 0.0.0.0  # Runs the MLflow server accessible from any network interface

networks:
  backend:  # Internal network for service-to-service communication
  frontend:  # Network for services that may need external access

volumes:
  bike_db_data:  # Volume for persisting PostgreSQL data
  bike_minio_data:  # Volume for persisting MinIO data
